# Generated by Django 3.1.7 on 2021-06-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_auto_20210630_1122"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="category",
            field=models.CharField(
                choices=[
                    ("Income", "Income"),
                    ("Bonus", "Bonus"),
                    ("Side Husttle", "Side Husttle"),
                    ("Others", "Others"),
                ],
                max_length=50,
            ),
        ),
    ]
